### ISSUE TITLE
Documentation/Examples?

### ISSUE THREAD

**Issue by igor-krawczuk** [JuliaParallel/Dagger.jl#103]
Hi, is there someplace with  more documentation/examples/tutorials? Or is one required to read the source code?

**Comment by jpsamaroo** [comment]
I think that it would be nice to have these pieces of documentation:

- Examples of some common algorithms rewritten to use Dagger
- An example of a very simple round-robin or stochastic scheduler that has plenty of inline code comments indicating what each piece of the code is doing
- Some more inline code comments on the current scheduler, explaining what more complicated pieces of code are doing

**Comment by jpsamaroo** [comment]
Ok, here's an initial list of things I'd like to know. Any answers I get, along with anything I figure out while hacking on the codebase, will end up getting sent in as a documentation PR:

- In the `state` struct that's used within the scheduler, in what case do we place a thunk in `state.ready`, versus having it pointed to by a "parent thunk" within `state.waiting`? Should a thunk, whose full set of dependents are either running or cached, be *always* placed in `state.ready`, and when it's in there, should it also always have a mapping from itself to its dependents in `state.waiting`?
- What is "affinity", and why does calling `affinity(t)` on thunk `t` often leave me with an empty container instead of whatever affinity is supposed to be associated with that thunk? I would expect it has something to do with what worker that thunk should next run on, but I've never been able to confirm it.
- Assumption: `fire_task!` places the specified thunk `t` on some worker and adds it to `state.running`, and places thunks that depend on `t` in `state.ready`.
- Assumption: `pop_with_affinity!` removes the thunk with the highest affinity, or just picks the first one it finds, from `state.ready`. Does this mean that `state.ready` must always be populated with at least one thunk, or will it be taken from `state.waiting`?
- What exactly are the things that `finish_task!` accomplishes?
- Is there a paper that I can refer to that gives details on the scheduler?

Sorry if some of these are obvious from the code, but it's been really hard to wrap my head around things while working on the fault tolerance PR...

**Comment by OkonSamuel** [comment]
@jpsamaroo. How is the documentation coming. Having some documentation will certainly help users and potential devs

**Comment by jpsamaroo** [comment]
@OkonSamuel I actually am working on a large write-up of Dagger's scheduler internals right now, which will end up becoming a PR for Dagger "devdocs" (documentation for contributors to Dagger). However, recent PRs should've made the README at least mostly accurate. Is there something in particular that you've found is incorrect, or is missing?

**Comment by OkonSamuel** [comment]
@jpsamaroo. Wow sounds like a lot of work. Anyways I said the README wan't up to date because can't seem to find any reference to `Dagger.Sch.SchedulerOptions` and `Dagger.Sch.ThunkOptions`. Am using `Dagger V0.8`. Are they types or Modules names

**Comment by jpsamaroo** [comment]
Oh, right, those are only defined on Dagger master; we haven't yet cut a release for all of the latest work. That should be rectified in the next few weeks.

P.S. They are `struct` s which are used to pass options to the scheduler and individual thunks.

**Comment by bjarthur** [comment]
an example of how to use `proctypes` would help a lot.  in my case, my thunks require various amounts of cores, memory, and maybe a gpu or not (e.g. one needs 12 cores, and 1GB, another 2 cores and a GPU).  how do i specify that?  the README just says it is possible, and the docstrings do not provide sufficient details for a new user.  so specifically, how should i use `Distributed.addprocs` and how do i associate a `Processor` type to each worker?
