### ISSUE TITLE
Distribute to WorkerPools

### ISSUE THREAD

**Issue by caseykneale** [JuliaParallel/Dagger.jl#115]
Could we get a convenience function to make Dagger tasking limited to only a prescribed WorkerPool? In it's simplest form, this is just a vector of process ID's.

**Comment by DrChainsaw** [comment]
I think this is possible by passing a Context, e.g.

```julia
collect(Context(procids), thunks)
```
with #147 it is also possible to modify which workers are available while the scheduler is running.

**Comment by jpsamaroo** [comment]
I don't think Dagger actually needs a convenience function for this, since we don't maintain the semantics required by `AbstractWorkerPool` (that we'll properly share computing resources with the other users of the pool). The one thing we might want is what `CachingPool` provides by caching serialized functions and closures; I'll file a separate issue to track that.
