### ISSUE TITLE
Fault handler masks exceptions

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaParallel/Dagger.jl#152]
The fault handler throws an exception when it is out of processes and unfortunately this masks any exceptions thrown from the dead worker(s).

This could probably be handled by a try/catch around `handle_fault`, but perhaps a more general mechanism to collect exceptions from all dead workers and return them to the user would be quite helpful. 

I'm not sure what is the best way to do the latter as in general the user might want to be able to see exceptions even if the job ultimately succeeds. 

Perhaps just printing out the whole stacktrace at the point where today a generic ` Warning: Worker 8 died on thunk 35, rescheduling work` is displayed. A verbosity flag can be used to toggle the behaviour in case this behaviour is not always wanted. 

Btw, I ran into this issue with a computation which succeeds when running locally but fails when running on another machine.

**Comment by jpsamaroo** [comment]
The fault handler generally handles the case where the failure is due to process exit, which I had originally assumed would only be due to something like OOM or segfault, which terminates the process immediately. However, there could certainly be an associated stacktrace in the exception. I definitely agree that we should print that trace, even if the computation does eventually succeed, because the user may want to know *why* the workers were exiting. A pair of `Base.showerror` and `Base.show_exception` on the received error sounds like a decent approach to me (although we should still display the warning message to make it clear we're doing something about the failure). We can have a flag to disable the error printing if you want, although I'd consider that optional.

**Comment by DrChainsaw** [comment]
Hmmm, I was thinking that any exception would lead to task restart, but it seems like `check_exited_exception` only return true for `ProcessExitedException` and `IOError`. For other exceptions, the exception is rethrown. 

Perhaps this is not needed after all, or what do you say?

**Comment by jpsamaroo** [comment]
Oh, yeah sorry, I thought there was potentially a stacktrace that we weren't showing. But in those two cases, it's usually because the process flat-out died, and is unrecoverable on that (now dead) worker. If you think we still should show the stacktrace for that error, then I'd be open to a PR.

**Comment by DrChainsaw** [comment]
>I thought there was potentially a stacktrace that we weren't showing

There might be, but I don't think so (ProcessExitedException does not seem to have it, haven't seen what comes in Base.IOError). As far as I understand now, the code basically does exactly what I think I wanted. Basically all (julia) user errors will be rethrown immediately.

It just seems that the cluster is killing my jobs without giving me any reason and I will try to investigate that with the admins :/

**Comment by jpsamaroo** [comment]
@tbenst oh I see, this happens because we also catch `IOError` since worker disconnects would sometimes manifest via socket closure. The new mechanism for detecting worker disconnects is potentially immune to this, so I've posted https://github.com/JuliaParallel/Dagger.jl/pull/245 which should unmask such errors.
