### ISSUE TITLE
Multithreading in simple case

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaParallel/Dagger.jl#161]
I'm using FileTrees.jl with one worker and 20 threads and I see that all the work is scheduled mostly on one thread.
Here is a MWE
```julia
using FileTrees
using CSV, DataFrames
using FileIO

t = maketree("mydir" => [])
@time for i = 1:10
    global t = touch(t, "$i.jpg")
end

@time t1 = FileTrees.load(t; lazy=true) do file
    rand(RGB, 10000, 10000)
end

@time FileTrees.save(t1) do file
    FileIO.save(string(path(file)), get(file))
end |> exec

@time t1 = FileTrees.load(t; lazy=true) do f
    img = FileIO.load(string(path(f)))
    println("threadid ", Threads.threadid(), ": ", path(f))
    red.(img)
end

mapvalues(mean, t1) |> exec
```
This gives me
```
threadid 4: mydir/1.jpg
threadid 3: mydir/10.jpg
threadid 3: mydir/2.jpg
threadid 3: mydir/3.jpg
threadid 3: mydir/4.jpg
threadid 3: mydir/5.jpg
threadid 3: mydir/6.jpg
threadid 3: mydir/7.jpg
threadid 3: mydir/8.jpg
threadid 3: mydir/9.jpg
```

I'm on Dagger v0.10.0, FileTrees v0.1.4 and
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_DEPOT_PATH = /mnt/storage/sebastian/.julia
  JULIA_EDITOR = "/home/sebastian/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/bin/code"
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_NUM_THREADS = 20
  JULIA_PATH = /usr/local/julia
  JULIA_VERSION = 1.5.2
```

**Comment by jpsamaroo** [comment]
This is probably a case that would be fixed by #141 , since right now we only schedule a single thunk (unit of work) per worker process. That PR instead schedules up to the total number of processors (in this case, total threads) onto each worker at once. I'll try to get that PR passing tests so it can be merged.

**Comment by jpsamaroo** [comment]
I just pushed a new set of changes to #141, can you give that a try? If you get any `KeyError`s, just rerun the code once or twice (it's a known issue and is non-deterministic in nature).

**Comment by SebastianM-C** [comment]
Thanks! I've tried it and it fixes the issue.

**Comment by shashi** [comment]
Can't we solve this just by having the scheduler schedule N tasks per process where N is the number of threads on it?

**Comment by shashi** [comment]
As `Context([1,1,1,1,2,2,2,2])` would do...

**Comment by jpsamaroo** [comment]
Yes, but that requires you to know in advance (or manually compute) the number of processors/threads/etc. that you want to make available on each worker. With my worker pressure PR, Dagger does this for you (since `ThreadProc` instances are automatically instantiated based on `Threads.nthreads` for each worker at load time).

**Comment by shashi** [comment]
Sounds good!
