### ISSUE TITLE
[feature request] @sync macro

### ISSUE THREAD

**Issue by tbenst** [JuliaParallel/Dagger.jl#260]
A lot of example code that uses `@distributed` or `@thread` does so in conjunction with the `@sync` macro, and would otherwise have undefined behavior. Some exemplars can be found at https://docs.julialang.org/en/v1/manual/distributed-computing/, for example.

It would be nice if Dagger had a similar mechanism to aid in translating code to Dagger from vanilla Julia.

**Comment by jpsamaroo** [comment]
Agreed! If you want to implement this it would be pretty easy: just look at the definitions of `@async`/`Threads.@spawn`; they check for the presence of a local variable and if present, they push a `Task` into it. We could just spawn a task that `wait`s on the `EagerThunk` returned from `Dagger.spawn`.

Otherwise, once I get some critical bugs fixed, I'll implement it myself.

**Comment by tbenst** [comment]
Cool, thanks! Crunch time for a paper can take a stab after if you haven’t beat me to it :)
