### ISSUE TITLE
Can `Dagger.@spawn` be used instead of `@async`?

### ISSUE THREAD

**Issue by schlichtanders** [JuliaParallel/Dagger.jl#477]
The current documentation of `@aync` includes this warning

> Warning
>
>  It is strongly encouraged to favor Threads.@spawn over @async always even when no parallelism is required
>  especially in publicly distributed libraries. This is because a use of @async disables the migration of the parent
>  task across worker threads in the current implementation of Julia. Thus, seemingly innocent use of @async in a
>  library function can have a large impact on the performance of very different parts of user applications.

Hence a natural question is whether `Dagger.@spawn` can also be used as a better alternative of `@async`. This would be so cool, as the whole concurrence interface would be unified.

If this indeed works, it would be great to have this somewhere obvious in the documentation.

**Comment by jpsamaroo** [comment]
In certain cases, yes, you can use `Dagger.@spawn` like either `Threads.@spawn` and `@async`, as it can express a function executed asynchronously either on the same thread, or a different one. However, the exact semantics differ in significant ways. Some of those differences are:
- `Dagger.@spawn` synchronization is performed implicitly, based on the passed arguments and any surrounding "task queues" that modify task synchronization behavior
- Dagger tasks are generally expected to *not* mutate or otherwise manipulate their arguments (unless using an API like `Dagger.spawn_datadeps`
- Dagger tasks are expected to always terminate, and generally should not loop forever, as that may block progress of other tasks (even if the Dagger task yields)
- Dagger will generally only run one task per thread, whereas `Threads.@spawn` and `@async` run multiple tasks per thread
- etc.
