### ISSUE TITLE
`_thunk_dict` is never cleaned up

### ISSUE THREAD

**Issue by tanmaykm** [JuliaParallel/Dagger.jl#76]
[`_thunk_dict`](https://github.com/JuliaParallel/Dagger.jl/blob/881109e279b66f31709ab29d85671b3590621663/src/thunk.jl#L8) can accumulate stuff over time and affect long running applications

**Comment by tanmaykm** [comment]
maybe it is safe to flush it after every `compute`?

**Comment by shashi** [comment]
It's not safe to do that... it's often the case that a previous DArray/DTable is reused, which may look up this dict..

**Comment by shashi** [comment]
Or rather the problem is 2 calls to `compute` with `@async` may flush the later compute's state. It looks to me like the only lookup of this dict https://github.com/JuliaParallel/Dagger.jl/blob/881109e279b66f31709ab29d85671b3590621663/src/compute.jl#L98 is per-compute. So the dict should really be in `ComputeState`... (we add to this when constructing a Thunk object - we should move that to init_state)

**Comment by jpsamaroo** [comment]
It appears that `_thunk_dict` is no longer a global variable and is now a part of `ComputeState` (thanks to https://github.com/JuliaParallel/Dagger.jl/commit/3a4e5676a0ed718dc1f2f071b5c80b4eea9f2a02), which should be sufficient to let the memory be freed once a DAG has completed running. So we should be able to close this issue, I would guess?
