### ISSUE TITLE
Scheduler tests not run

### ISSUE THREAD

**Issue by andreasnoack** [JuliaParallel/Dagger.jl#99]
The `test/scheduler.jl` file is currently not included in `runtests.jl`.

**Comment by jpsamaroo** [comment]
#107 added back the include to `runtests.jl`, however it also commented out all of the previous tests in there. Since those tests seemed to be isolated to testing `@par` (which doesn't seem to exist any longer), do we want to just remove those tests? I personally feel that such a macro would be a better fit for another package anyway, were it to be reimplemented.

**Comment by jpsamaroo** [comment]
Closing since the above-mentioned tests were removed.
